/* Velora's complete interface dictionary. English phrases are the stable keys so
   static HTML, accessible labels, placeholders, and dynamic UI share one source. */
const translations = {
  kz: {
    'A little something for you — complimentary delivery on orders over $120':'Сізге шағын сыйлық — $120-дан жоғары тапсырысқа жеткізу тегін',
    'Home':'Басты бет','Shop':'Дүкен','Our story':'Біздің тарих','Contact':'Байланыс','Search':'Іздеу','Shopping bag':'Сатып алу себеті','THE AUTUMN EDIT · 2025':'КҮЗГІ ЖИНАҚ · 2025',
    'Wear your':'Өз болмысыңды','own story.':'киіміңмен таныт.','Thoughtful pieces for wherever life takes you. Made to feel like you, every day.':'Өмір жолыңыз қайда апарса да, бірге болатын мәнді киімдер. Күн сайын өзіңіздікіндей сезіледі.','Discover the collection':'Жинақты көру','Designed with intention':'Әр бөлшегі ойластырылған','THE NEW':'ЖАҢА','STANDARD.':'СТАНДАРТ.','CONSIDERED MATERIALS':'ОЙЛАСТЫРЫЛҒАН МАТЕРИАЛДАР','MADE TO LAST':'ҰЗАҚ КИЮҒА АРНАЛҒАН','FREE SHIPPING OVER $120':'$120-ДАН ЖОҒАРЫ ТЕГІН ЖЕТКІЗУ','EASY 30-DAY RETURNS':'30 КҮН ІШІНДЕ ОҢАЙ ҚАЙТАРУ',
    'THE GOOD STUFF':'ЕҢ ЖАҚСЫСЫ','Pieces you\'ll keep.':'Ұзақ киетін киімдер.','Shop all pieces':'Барлық киімді көру','A NEW POINT OF VIEW':'ЖАҢА КӨЗҚАРАС','Less, but':'Аз, бірақ','better.':'сапалы.','Good clothes have a way of making everything else feel easier. We make fewer, better things — designed to become part of your everyday.':'Жақсы киім күнделікті өмірді жеңілдетеді. Біз аз, бірақ сапалы әрі күнделікті киюге арналған бұйым жасаймыз.','Get to know us':'Біз туралы','JUST LANDED':'ЖАҢА ТҮСТІ','New in, naturally.':'Жаңа дүние — өзіңізге лайық.','See what\'s new':'Жаңалықтарды көру','FIND YOUR THING':'ӨЗІҢІЗГЕ ЛАЙЫҒЫН ТАБЫҢЫЗ','A good place to start.':'Таңдауды осыдан бастаңыз.','01 — THE EVERYDAY':'01 — КҮНДЕЛІКТІ КИІМ','02 — THE CLASSICS':'02 — КЛАССИКА','03 — FROM THE GROUND UP':'03 — АЯҚКИІМ','04 — THE FINISHING TOUCH':'04 — СОҢҒЫ ӘШЕКЕЙ','Women':'Әйелдер','Men':'Ерлер','Shoes':'Аяқкиім','Accessories':'Керек-жарақ',
    'KIND WORDS, WORN OFTEN':'ЖҮРЕКТЕН ШЫҚҚАН ПІКІР','“Finally, clothes that feel like me and somehow go with everything I already own.”':'«Ақыры өзіме сай әрі гардеробымдағының бәрімен жарасатын киім таптым».','MAYA R.   ·   VERIFIED CUSTOMER':'МАЙЯ Р. · ТЕКСЕРІЛГЕН САТЫП АЛУШЫ','LIFE IN VELO​RA':'VELO​RA ӨМІР САЛТЫ','Good company, good clothes.':'Жақсы орта, жақсы киім.','A LETTER FROM US':'БІЗДЕН ХАТ','Consider this your good inbox.':'Поштаңызға жақсы жаңалық келсін.','New arrivals, little stories, and 10% off your first order.':'Жаңа топтамалар, шағын оқиғалар және алғашқы тапсырысқа 10% жеңілдік.','Your email address':'Электрондық поштаңыз','By signing up, you agree to receive the occasional email from Velora.':'Тіркелу арқылы Velora хабарламаларын алуға келісесіз.',
    'Everyday things, made extraordinary.':'Күнделікті дүниелерді ерекше етеміз.','EXPLORE':'ЗЕРТТЕУ','THE DETAILS':'МӘЛІМЕТТЕР','SAY HELLO':'БІЗБЕН БАЙЛАНЫС','Shop all':'Барлығын көру','Get in touch':'Байланысу','Shipping & returns':'Жеткізу және қайтару','FAQs':'Жиі қойылатын сұрақтар','Studio':'Студия','Made with care, worn with joy.':'Ықыласпен жасалған, қуанышпен киілетін киім.','Privacy':'Құпиялылық','Terms':'Шарттар',
    'What are you looking for?':'Не іздеп жүрсіз?','Your bag':'Себетіңіз','Subtotal':'Аралық сома','Shipping calculated at checkout.':'Жеткізу құны төлем кезінде есептеледі.','Continue to checkout →':'Төлемге өту →','Your bag is taking a little breather.':'Себетіңіз әзірге бос.','Find something lovely →':'Өзіңізге ұнайтын зат табыңыз →','Complimentary shipping over $120':'$120-дан жоғары тапсырысқа жеткізу тегін','Easy 30-day returns':'30 күн ішінде оңай қайтару','Thoughtfully made to last':'Ұзақ киюге лайықтап жасалған',
    'THE VE​LORA COLLECTION':'VE​LORA ЖИНАҒЫ','Good things, in good company.':'Жақсы дүниелер — жақсы таңдаумен.','Thoughtful pieces to wear on repeat. Find the ones that feel like you.':'Қайта-қайта кигіңіз келетін мәнді киімдер. Өзіңізге сай келетінін таңдаңыз.','Everything':'Барлығы','♡ Saved':'♡ Таңдаулылар','REFINE YOUR EDIT':'ТАҢДАУДЫ СҮЗГІЛЕУ','Category':'Санат','All pieces':'Барлық киім','Try a linen shirt...':'Зығыр жейде іздеу...','Price range':'Баға аралығы','Up to':'Дейін','Clear all filters ×':'Сүзгілерді тазарту ×','A wardrobe with a lighter footprint.':'Ұқыпты гардероб.','Good clothes, made to last.':'Ұзақ киюге арналған сапалы киім.','pieces':'зат','piece':'зат','Complimentary shipping over $120':'$120-дан жоғары тапсырысқа жеткізу тегін','No pieces found. Try adjusting your filters.':'Ештеңе табылмады. Сүзгілерді өзгертіп көріңіз.','Sort by':'Сұрыптау','Featured':'Таңдаулы','What\'s new':'Жаңалары','Price: low to high':'Бағасы: алдымен арзаны','Price: high to low':'Бағасы: алдымен қымбаты',
    'Details':'Мәлімет','THOUGHTFULLY MADE':'ЫҚЫЛАСПЕН ЖАСАЛҒАН','reviews':'пікір','CHOOSE YOUR SIZE':'ӨЛШЕМДІ ТАҢДАҢЫЗ','Size guide':'Өлшем кестесі','Add to your bag':'Себетке қосу','♡ Save for later':'♡ Таңдаулыларға қосу','♥ Saved to your wishlist':'♥ Таңдаулыларға сақталды','Ask us about this piece on WhatsApp':'Бұл киім туралы WhatsApp арқылы сұраңыз','REAL PEOPLE, REAL GOOD TASTE':'ШЫН АДАМДАРДЫҢ ШЫН ПІКІРІ','A few kind words.':'Жылы лебіздер.','“The kind of piece that makes getting dressed feel effortless.”':'«Киінуді оңай әрі жағымды ететін киім».','“Beautiful quality, and I can wear it with absolutely everything.”':'«Сапасы керемет, кез келген киіммен үйлеседі».','“It fits perfectly. The fabric feels even better than I expected.”':'«Дәл жарасады. Матасы күткенімнен де жақсы».','VERIFIED CUSTOMER':'ТЕКСЕРІЛГЕН САТЫП АЛУШЫ',
    'A NOTE FROM US':'БІЗДЕН БІР АУЫЗ СӨЗ','Good clothes.':'Жақсы киім.','Good intentions.':'Жақсы ниет.','We believe getting dressed should feel simple, personal, and a little bit joyful.':'Киіну оңай, өзіңізге сай және аздап қуанышты болуы керек деп сенеміз.','WHY VE​LORA EXISTS':'VELO​RA НЕ ҮШІН ҚҰРЫЛДЫ','A smaller wardrobe.':'Шағын гардероб.','A bigger feeling.':'Үлкен әсер.','Velora started with a question: what if your favourite clothes were also the ones you reached for most? We design calm, versatile pieces around real lives, not passing trends.':'Velora бір сұрақтан басталды: сүйікті киіміңіз ең жиі киетін киіміңіз болса ше? Біз өткінші трендке емес, күнделікті өмірге лайық әмбебап киім жасаймыз.','Every collection is a considered edit: comfortable fabrics, thoughtful details, and shapes you\'ll want to wear on an ordinary Tuesday. We believe good style should feel like you — and last a little longer.':'Әр топтамада жайлы мата, ойластырылған бөлшек және күнделікті киюге ыңғайлы пішім бар. Жақсы стиль өзіңіздікіндей сезіліп, ұзаққа жарауы керек.','Find your everyday':'Күнделікті киіміңізді табыңыз','OUR LITTLE PROMISES':'БІЗДІҢ УӘДЕМІЗ','Made with a point of view.':'Өз ұстанымымызбен жасалған.','Buy less, love more.':'Аз алыңыз, ұзағырақ сүйіп киіңіз.','We make thoughtfully, so the pieces you choose can stay in your life for seasons to come.':'Таңдаған киіміңіз бірнеше маусым бойы жаныңыздан табылуы үшін мұқият жасаймыз.','Details matter.':'Бөлшектер маңызды.','From a pocket that lands just right to fabrics that feel lovely against your skin.':'Дәл орнында тігілген қалтадан бастап, теріге жағымды матаға дейін.','Easy does it.':'Киіну оңай болсын.','Getting dressed should be the easiest part of your day. We make clothes that play well together.':'Киіну күніңіздің ең оңай бөлігі болуы керек. Біз бір-бірімен үйлесетін киім жасаймыз.',
    'WE\'RE ALL EARS':'СІЗДІ ТЫҢДАУҒА ДАЙЫНБЫЗ','Let\'s talk things through.':'Бәрін бірге талқылайық.','A fit question, an order update, or just a hello — we’re listening.':'Өлшем, тапсырыс туралы сұрақ немесе жай ғана сәлем — біз тыңдауға дайынбыз.','A REAL HUMAN, PROMISE':'СІЗГЕ НАҚТЫ АДАМ ЖАУАП БЕРЕДІ','Here for you.':'Сізге көмектесеміз.','Our small team usually replies within one working day. Send us a note and we’ll take it from there.':'Шағын тобымыз әдетте бір жұмыс күні ішінде жауап береді. Хабарлама жіберіңіз.','Monday to Friday, 9am–5pm':'Дүйсенбі–жұма, 9:00–17:00','Your name':'Аты-жөніңіз','First and last name':'Аты-жөніңізді енгізіңіз','Email address':'Электрондық пошта','you@example.com':'you@example.com','What can we help with?':'Қандай көмек керек?','Something else':'Басқа сұрақ','My order':'Тапсырысым','Sizing and fit':'Өлшем және қоным','Shipping and returns':'Жеткізу және қайтару','Press and partnerships':'Баспасөз және серіктестік','Your message':'Хабарламаңыз','Tell us what\'s on your mind...':'Не туралы айтқыңыз келетінін жазыңыз...','Send your note':'Хабарлама жіберу','THE QUICK ANSWERS':'ЖИІ ҚОЙЫЛАТЫН СҰРАҚТАР','A few things you might be wondering.':'Сізді қызықтыруы мүмкін сұрақтар.','When will my order arrive?':'Тапсырысым қашан келеді?','Standard delivery usually takes 3–5 working days. You\'ll receive a note from us as soon as your parcel is on its way.':'Әдеттегі жеткізу 3–5 жұмыс күнін алады. Сәлемдеме жолға шыққанда хабарлаймыз.','Can I return something that doesn\'t feel right?':'Ұнамаған тауарды қайтара аламын ба?','Of course. You have 30 days from delivery to return unworn items in their original condition. Get in touch and we\'ll help.':'Әрине. Жеткізілген күннен бастап 30 күн ішінде киілмеген тауарды бастапқы күйінде қайтара аласыз. Бізге хабарласыңыз.','How can I find the right size?':'Өлшемімді қалай анықтаймын?','Our pieces are designed to fit true to size. If you are between sizes, or need a hand, send us a note and we will help you find your fit.':'Киімдер өлшем кестесіне сай келеді. Екі өлшемнің арасында болсаңыз немесе көмек керек болса, бізге жазыңыз.',
    'Add to bag  +':'Себетке қосу  +','Add to bag &nbsp; +':'Себетке қосу  +','Remove':'Өшіру','Add':'Қосу','No pieces found. Try another search.':'Зат табылмады. Басқаша іздеп көріңіз.','Added to your bag — lovely choice.':'Себетке қосылды — тамаша таңдау.','Saved to your wishlist.':'Таңдаулыларға сақталды.','Removed from your wishlist.':'Таңдаулылардан өшірілді.','Thanks for getting in touch. Your note is ready for our team!':'Хабарласқаныңызға рақмет! Хабарламаңыз дайын.','You’re on the list. Thanks for being here!':'Тізімге қосылдыңыз. Рақмет!','Checkout is a demo — connect a payment provider to take live orders.':'Төлем — демо режимде. Нақты тапсырыс үшін төлем жүйесін қосыңыз.','Your bag is empty.':'Себетіңіз бос.','Piece not found.':'Тауар табылмады.','Return to the collection.':'Жинаққа оралу.','just in':'жаңа','JUST IN':'ЖАҢА','20% OFF':'20% ЖЕҢІЛДІК'
  },
  ru: {
    'A little something for you — complimentary delivery on orders over $120':'Небольшой подарок — бесплатная доставка при заказе от $120','Home':'Главная','Shop':'Магазин','Our story':'О нас','Contact':'Контакты','Search':'Поиск','Shopping bag':'Корзина','THE AUTUMN EDIT · 2025':'ОСЕННЯЯ КОЛЛЕКЦИЯ · 2025','Wear your':'Носи свою','own story.':'историю.','Thoughtful pieces for wherever life takes you. Made to feel like you, every day.':'Продуманные вещи для любого дня. Будь собой каждый день.','Discover the collection':'Открыть коллекцию','Designed with intention':'Создано с заботой','THE NEW':'НОВЫЙ','STANDARD.':'СТАНДАРТ.','CONSIDERED MATERIALS':'ПРОДУМАННЫЕ МАТЕРИАЛЫ','MADE TO LAST':'НАДОЛГО','FREE SHIPPING OVER $120':'БЕСПЛАТНАЯ ДОСТАВКА ОТ $120','EASY 30-DAY RETURNS':'ЛЁГКИЙ ВОЗВРАТ ЗА 30 ДНЕЙ',
    'THE GOOD STUFF':'САМОЕ ИНТЕРЕСНОЕ','Pieces you\'ll keep.':'Вещи, которые останутся.','Shop all pieces':'Все товары','A NEW POINT OF VIEW':'НОВЫЙ ВЗГЛЯД','Less, but':'Меньше, но','better.':'лучше.','Good clothes have a way of making everything else feel easier. We make fewer, better things — designed to become part of your everyday.':'Хорошая одежда делает каждый день проще. Мы создаём меньше вещей, но лучше — для вашей повседневной жизни.','Get to know us':'Познакомиться с нами','JUST LANDED':'ТОЛЬКО ПОЯВИЛОСЬ','New in, naturally.':'Новинки на каждый день.','See what\'s new':'Смотреть новинки','FIND YOUR THING':'НАЙДИТЕ СВОЁ','A good place to start.':'Начните отсюда.','01 — THE EVERYDAY':'01 — НА КАЖДЫЙ ДЕНЬ','02 — THE CLASSICS':'02 — КЛАССИКА','03 — FROM THE GROUND UP':'03 — ОБУВЬ','04 — THE FINISHING TOUCH':'04 — ДЕТАЛИ','Women':'Женское','Men':'Мужское','Shoes':'Обувь','Accessories':'Аксессуары',
    'KIND WORDS, WORN OFTEN':'ТЁПЛЫЕ ОТЗЫВЫ','“Finally, clothes that feel like me and somehow go with everything I already own.”':'«Наконец-то одежда, в которой я — это я, и которая подходит ко всему».','MAYA R.   ·   VERIFIED CUSTOMER':'МАЙЯ Р. · ПРОВЕРЕННЫЙ ПОКУПАТЕЛЬ','LIFE IN VELO​RA':'ЖИЗНЬ В VELO​RA','Good company, good clothes.':'Хорошая компания, хорошая одежда.','A LETTER FROM US':'ПИСЬМО ОТ НАС','Consider this your good inbox.':'Пусть в почте будет что-то хорошее.','New arrivals, little stories, and 10% off your first order.':'Новинки, небольшие истории и скидка 10% на первый заказ.','Your email address':'Ваш email','By signing up, you agree to receive the occasional email from Velora.':'Подписываясь, вы соглашаетесь получать письма от Velora.',
    'Everyday things, made extraordinary.':'Обычные вещи — особенные.','EXPLORE':'КОЛЛЕКЦИЯ','THE DETAILS':'ИНФОРМАЦИЯ','SAY HELLO':'НАПИШИТЕ НАМ','Shop all':'Все товары','Get in touch':'Связаться','Shipping & returns':'Доставка и возврат','FAQs':'Частые вопросы','Studio':'Студия','Made with care, worn with joy.':'Создано с заботой, носите с радостью.','Privacy':'Конфиденциальность','Terms':'Условия',
    'What are you looking for?':'Что вы ищете?','Your bag':'Ваша корзина','Subtotal':'Подытог','Shipping calculated at checkout.':'Стоимость доставки рассчитается при оплате.','Continue to checkout →':'Перейти к оплате →','Your bag is taking a little breather.':'В корзине пока пусто.','Find something lovely →':'Найти что-нибудь прекрасное →','Complimentary shipping over $120':'Бесплатная доставка от $120','Easy 30-day returns':'Лёгкий возврат за 30 дней','Thoughtfully made to last':'Продумано и надолго',
    'THE VE​LORA COLLECTION':'КОЛЛЕКЦИЯ VE​LORA','Good things, in good company.':'Хорошие вещи — в хорошей компании.','Thoughtful pieces to wear on repeat. Find the ones that feel like you.':'Продуманные вещи, которые хочется носить снова. Найдите свои.','Everything':'Всё','♡ Saved':'♡ Избранное','REFINE YOUR EDIT':'ФИЛЬТРЫ','Category':'Категория','All pieces':'Все товары','Try a linen shirt...':'Например, льняная рубашка...','Price range':'Диапазон цены','Up to':'До','Clear all filters ×':'Сбросить фильтры ×','A wardrobe with a lighter footprint.':'Осознанный гардероб.','Good clothes, made to last.':'Хорошая одежда надолго.','pieces':'товаров','piece':'товар','No pieces found. Try adjusting your filters.':'Ничего не найдено. Измените фильтры.','Sort by':'Сортировка','Featured':'Рекомендуем','What\'s new':'Новинки','Price: low to high':'Сначала дешевле','Price: high to low':'Сначала дороже',
    'Details':'Подробнее','THOUGHTFULLY MADE':'СОЗДАНО С ЗАБОТОЙ','reviews':'отзывов','CHOOSE YOUR SIZE':'ВЫБЕРИТЕ РАЗМЕР','Size guide':'Таблица размеров','Add to your bag':'В корзину','♡ Save for later':'♡ В избранное','♥ Saved to your wishlist':'♥ В избранном','Ask us about this piece on WhatsApp':'Спросить об этой вещи в WhatsApp','REAL PEOPLE, REAL GOOD TASTE':'НАСТОЯЩИЕ ОТЗЫВЫ','A few kind words.':'Несколько тёплых слов.','“The kind of piece that makes getting dressed feel effortless.”':'«Вещь, с которой собираться легко и приятно».','“Beautiful quality, and I can wear it with absolutely everything.”':'«Прекрасное качество, подходит ко всему».','“It fits perfectly. The fabric feels even better than I expected.”':'«Идеальная посадка, ткань лучше, чем ожидала».','VERIFIED CUSTOMER':'ПРОВЕРЕННЫЙ ПОКУПАТЕЛЬ',
    'A NOTE FROM US':'ПАРА СЛОВ ОТ НАС','Good clothes.':'Хорошая одежда.','Good intentions.':'Добрые намерения.','We believe getting dressed should feel simple, personal, and a little bit joyful.':'Одеваться должно быть просто, удобно и немного радостно.','WHY VE​LORA EXISTS':'ЗАЧЕМ НУЖНА VE​LORA','A smaller wardrobe.':'Гардероб поменьше.','A bigger feeling.':'Ощущений побольше.','Velora started with a question: what if your favourite clothes were also the ones you reached for most? We design calm, versatile pieces around real lives, not passing trends.':'Velora началась с вопроса: что, если любимая одежда станет той, что вы носите чаще всего? Мы создаём универсальные вещи для жизни, а не мимолётных трендов.','Every collection is a considered edit: comfortable fabrics, thoughtful details, and shapes you\'ll want to wear on an ordinary Tuesday. We believe good style should feel like you — and last a little longer.':'В каждой коллекции — комфортные ткани, продуманные детали и вещи на каждый день. Хороший стиль должен быть вашим и служить дольше.','Find your everyday':'Найдите свою повседневную вещь','OUR LITTLE PROMISES':'НАШИ ОБЕЩАНИЯ','Made with a point of view.':'Создано со смыслом.','Buy less, love more.':'Покупайте меньше, любите дольше.','We make thoughtfully, so the pieces you choose can stay in your life for seasons to come.':'Мы создаём вещи, которые останутся с вами на несколько сезонов.','Details matter.':'Детали важны.','From a pocket that lands just right to fabrics that feel lovely against your skin.':'От удобного кармана до приятной к телу ткани.','Easy does it.':'Пусть будет просто.','Getting dressed should be the easiest part of your day. We make clothes that play well together.':'Одежда должна быть самой простой частью дня. Наши вещи сочетаются между собой.',
    'WE\'RE ALL EARS':'МЫ ВАС СЛУШАЕМ','Let\'s talk things through.':'Давайте обсудим.','A fit question, an order update, or just a hello — we’re listening.':'Вопрос о размере, заказе или просто привет — мы на связи.','A REAL HUMAN, PROMISE':'ОТВЕТИТ ЖИВОЙ ЧЕЛОВЕК','Here for you.':'Мы рядом.','Our small team usually replies within one working day. Send us a note and we’ll take it from there.':'Наша команда обычно отвечает в течение рабочего дня. Напишите нам — и мы поможем.','Monday to Friday, 9am–5pm':'Понедельник–пятница, 9:00–17:00','Your name':'Ваше имя','First and last name':'Имя и фамилия','Email address':'Электронная почта','you@example.com':'you@example.com','What can we help with?':'Чем можем помочь?','Something else':'Другое','My order':'Мой заказ','Sizing and fit':'Размер и посадка','Shipping and returns':'Доставка и возврат','Press and partnerships':'Пресса и партнёрство','Your message':'Ваше сообщение','Tell us what\'s on your mind...':'Расскажите, что вас интересует...','Send your note':'Отправить сообщение','THE QUICK ANSWERS':'КОРОТКО О ГЛАВНОМ','A few things you might be wondering.':'Ответы на частые вопросы.','When will my order arrive?':'Когда придёт мой заказ?','Standard delivery usually takes 3–5 working days. You\'ll receive a note from us as soon as your parcel is on its way.':'Обычно доставка занимает 3–5 рабочих дней. Мы сообщим, когда посылка отправится.','Can I return something that doesn\'t feel right?':'Можно ли вернуть неподошедшую вещь?','Of course. You have 30 days from delivery to return unworn items in their original condition. Get in touch and we\'ll help.':'Конечно. Верните неношеную вещь в исходном состоянии в течение 30 дней. Напишите нам — поможем.','How can I find the right size?':'Как выбрать размер?','Our pieces are designed to fit true to size. If you are between sizes, or need a hand, send us a note and we will help you find your fit.':'Размеры соответствуют таблице. Если сомневаетесь или нужна помощь, напишите нам.',
    'Add to bag  +':'В корзину  +','Add to bag &nbsp; +':'В корзину  +','Remove':'Убрать','Add':'Добавить','No pieces found. Try another search.':'Ничего не найдено. Попробуйте другой запрос.','Added to your bag — lovely choice.':'Добавлено в корзину — отличный выбор.','Saved to your wishlist.':'Добавлено в избранное.','Removed from your wishlist.':'Удалено из избранного.','Thanks for getting in touch. Your note is ready for our team!':'Спасибо за сообщение! Мы скоро с вами свяжемся.','You’re on the list. Thanks for being here!':'Вы в списке. Спасибо!','Checkout is a demo — connect a payment provider to take live orders.':'Оплата демонстрационная. Для заказов подключите платёжный сервис.','Your bag is empty.':'Корзина пуста.','Piece not found.':'Товар не найден.','Return to the collection.':'Вернуться в каталог.','just in':'новинка','JUST IN':'НОВИНКА','20% OFF':'СКИДКА 20%'
  },
  en: {}
};
Object.assign(translations.kz, {
  'Velora — Wear your own story':'Velora — Өзіңнің тарихыңды ки',
  'The Everyday Linen Shirt':'Күнделікті зығыр жейде','Relaxed Tailored Trouser':'Еркін пішімді классикалық шалбар','The Weekend Knit':'Демалысқа арналған тоқыма жемпір','Soft Structure Tote':'Пішіні жинақы жұмсақ сөмке','City Walk Loafer':'Қалаға арналған лофер','Sunday Cotton Tee':'Жексенбілік мақта футболкасы','The Everyday Midi':'Күнделікті миди көйлек','Leather Weekender':'Былғары жол сөмкесі',
  'An easy layer for slow mornings and full days. Cut from airy, breathable linen with a relaxed shape that feels just right.':'Жайма-шуақ таң мен қарбалас күнге арналған жеңіл қабат. Ауа өткізетін зығырдан еркін пішімде тігілген.',
  'A flattering drape with the ease of your favourite pair. Finished with a soft waistband, deep pockets, and a clean tailored line.':'Сүйікті шалбарыңыздай жайлы, әдемі қонымды үлгі. Жұмсақ белдігі, терең қалталары және жинақы пішімі бар.',
  'A quietly handsome knit in soft, breathable cotton. An everyday layer made for all the little in-between moments.':'Жұмсақ, ауа өткізетін мақтадан тоқылған күнделікті жемпір. Күн арасындағы сәттерге арналған.',
  'A thoughtful carryall that holds all your everyday essentials. Crafted with room to roam, inside and out.':'Күнделікті қажетті заттарыңызға арналған сөмке. Кең әрі ішкі қалталары ойластырылған.',
  'Meet your go-anywhere shoe. A clean, considered silhouette with a cushioned sole designed for a full day on your feet.':'Кез келген жерге киюге болатын аяқкиім. Жұмсақ ұлтанымен күні бойы жайлылық сыйлайды.',
  'The tee you reach for without thinking. Made from soft organic cotton with an easy, everyday fit.':'Ойланбастан қайта-қайта киетін футболка. Жұмсақ органикалық мақтадан еркін пішімде тігілген.',
  'An effortless throw-on-and-go dress, made for wherever the day takes you. Light, lovely, and easy to make your own.':'Күнделікті киюге арналған жеңіл көйлек. Жайлы, әдемі және әртүрлі үйлестіруге оңай.',
  'A considered companion for short escapes and everyday carry. Roomy, sturdy, and all the better for a little adventure.':'Қысқа сапар мен күнделікті заттарға арналған былғары сөмке. Кең, берік, жолға дайын.'
});
Object.assign(translations.ru, {
  'Velora — Wear your own story':'Velora — Носи свою историю',
  'The Everyday Linen Shirt':'Повседневная льняная рубашка','Relaxed Tailored Trouser':'Свободные классические брюки','The Weekend Knit':'Свитер для выходных','Soft Structure Tote':'Мягкая структурная сумка','City Walk Loafer':'Лоферы для прогулок по городу','Sunday Cotton Tee':'Хлопковая футболка на каждый день','The Everyday Midi':'Повседневное платье миди','Leather Weekender':'Кожаная дорожная сумка',
  'An easy layer for slow mornings and full days. Cut from airy, breathable linen with a relaxed shape that feels just right.':'Лёгкий слой для спокойных утр и насыщенных дней. Дышащий лён и свободный крой.',
  'A flattering drape with the ease of your favourite pair. Finished with a soft waistband, deep pockets, and a clean tailored line.':'Элегантная посадка и комфорт любимых брюк. Мягкий пояс, глубокие карманы и лаконичный крой.',
  'A quietly handsome knit in soft, breathable cotton. An everyday layer made for all the little in-between moments.':'Мягкий дышащий хлопковый свитер на каждый день и на все промежуточные моменты.',
  'A thoughtful carryall that holds all your everyday essentials. Crafted with room to roam, inside and out.':'Вместительная сумка для всего необходимого на каждый день. Продуманное внутреннее пространство.',
  'Meet your go-anywhere shoe. A clean, considered silhouette with a cushioned sole designed for a full day on your feet.':'Универсальная пара с лаконичным силуэтом и мягкой подошвой для долгих прогулок.',
  'The tee you reach for without thinking. Made from soft organic cotton with an easy, everyday fit.':'Футболка, к которой тянешься не задумываясь. Мягкий органический хлопок и свободная посадка.',
  'An effortless throw-on-and-go dress, made for wherever the day takes you. Light, lovely, and easy to make your own.':'Лёгкое платье на каждый день. Удобное, красивое и простое в сочетаниях.',
  'A considered companion for short escapes and everyday carry. Roomy, sturdy, and all the better for a little adventure.':'Продуманная кожаная сумка для коротких поездок и повседневных дел. Вместительная и прочная.'
});
Object.assign(translations.kz, {
  'Wishlist':'Таңдаулылар','Toggle dark mode':'Қараңғы режимді ауыстыру','Open menu':'Мәзірді ашу','Close search':'Іздеуді жабу','Close bag':'Себетті жабу','Search products':'Тауарларды іздеу','Remove from':'ішінен өшіру','to':'ішіне','from':'ішінен','wishlist':'таңдаулылар','Add to bag +':'Себетке қосу +','Good things,':'Жақсы дүниелер,','in good company.':'жақсы таңдаумен.','Let\'s talk':'Сөйлесейік','things through.':'бәрін бірге талқылайық.','Message us on WhatsApp':'WhatsApp арқылы жазыңыз','Phone':'Телефон','Address':'Мекенжай','Details':'Мәлімет','No pieces found.':'Тауар табылмады.','What can we help with?':'Қандай көмек керек?','Price: low to high':'Бағасы: алдымен арзаны','Price: high to low':'Бағасы: алдымен қымбаты','New arrival':'Жаңа топтама',
  'Shop the collection — Velora':'Жинақты көру — Velora','Product details — Velora':'Тауар туралы — Velora','Our story — Velora':'Біздің тарих — Velora','Contact us — Velora':'Бізбен байланысу — Velora',
  'Good morning, Studio.':'Қайырлы күн, студия!','Here\'s a little look at how things are going.':'Жұмыстардың қысқаша көрінісі.','TOTAL SALES':'ЖАЛПЫ САТЫЛЫМ','ORDERS':'ТАПСЫРЫСТАР','PRODUCTS':'ТАУАРЛАР','CUSTOMERS':'КЛИЕНТТЕР','this month':'осы айда','Across 4 categories':'4 санат бойынша','Sales at a glance':'Сатылымға шолу','Recent orders':'Соңғы тапсырыстар','Your products.':'Тауарларыңыз.','A considered edit of everything you offer.':'Ұсынатын тауарларыңыздың жинағы.','Add a product':'Тауар қосу','PRODUCT':'ТАУАР','CATEGORY':'САНАТ','PRICE':'БАҒА','STATUS':'КҮЙІ','Edit':'Өзгерту','Delete':'Жою','Active':'Белсенді','Your categories.':'Санаттарыңыз.','Organise your edit, your way.':'Жинақты өзіңізге ыңғайлы реттеңіз.','Add a category':'Санат қосу','PRODUCTS':'ТАУАРЛАР','Remove':'Өшіру','Orders.':'Тапсырыстар.','A little overview of what\'s on its way.':'Жолдағы тапсырыстарға қысқаша шолу.','ORDER':'ТАПСЫРЫС','CUSTOMER':'КЛИЕНТ','TOTAL':'БАРЛЫҒЫ','DATE':'КҮНІ','Processing':'Өңделуде','Shipped':'Жіберілді','Delivered':'Жеткізілді','Customers.':'Клиенттер.','Lovely people, lovely choices.':'Тамаша адамдар, тамаша таңдау.','EMAIL':'ЭЛЕКТРОНДЫҚ ПОШТА','SPENT':'ЖҰМСАЛҒАНЫ','LAST ORDER':'СОҢҒЫ ТАПСЫРЫС','Add product':'Тауар қосу','Product name':'Тауар атауы','Compare at price':'Бұрынғы баға','Image file ID':'Сурет файлының ID-і','Short description':'Қысқаша сипаттама','New arrival':'Жаңа топтама','Save product':'Тауарды сақтау','Cancel':'Болдырмау','Category name':'Санат атауы','Save category':'Санатты сақтау','Move or remove this category’s products first.':'Алдымен осы санаттағы тауарларды ауыстырыңыз немесе өшіріңіз.'
});
Object.assign(translations.ru, {
  'Wishlist':'Избранное','Toggle dark mode':'Переключить тёмную тему','Open menu':'Открыть меню','Close search':'Закрыть поиск','Close bag':'Закрыть корзину','Search products':'Поиск товаров','Remove from':'убрать из','to':'в','from':'из','wishlist':'избранного','Add to bag +':'В корзину +','Good things,':'Хорошие вещи,','in good company.':'в хорошей компании.','Let\'s talk':'Давайте','things through.':'всё обсудим.','Message us on WhatsApp':'Написать нам в WhatsApp','Phone':'Телефон','Address':'Адрес','Details':'Подробнее','No pieces found.':'Товары не найдены.','New arrival':'Новинка',
  'Shop the collection — Velora':'Коллекция — Velora','Product details — Velora':'О товаре — Velora','Our story — Velora':'О нас — Velora','Contact us — Velora':'Связаться — Velora',
  'Good morning, Studio.':'Доброе утро, студия!','Here\'s a little look at how things are going.':'Краткий обзор дел.','TOTAL SALES':'ОБЩИЕ ПРОДАЖИ','ORDERS':'ЗАКАЗЫ','PRODUCTS':'ТОВАРЫ','CUSTOMERS':'КЛИЕНТЫ','this month':'в этом месяце','Across 4 categories':'В 4 категориях','Sales at a glance':'Обзор продаж','Recent orders':'Последние заказы','Your products.':'Ваши товары.','A considered edit of everything you offer.':'Продуманная подборка ваших товаров.','Add a product':'Добавить товар','PRODUCT':'ТОВАР','CATEGORY':'КАТЕГОРИЯ','PRICE':'ЦЕНА','STATUS':'СТАТУС','Edit':'Изменить','Delete':'Удалить','Active':'Активен','Your categories.':'Ваши категории.','Organise your edit, your way.':'Организуйте коллекцию по-своему.','Add a category':'Добавить категорию','Remove':'Убрать','Orders.':'Заказы.','A little overview of what\'s on its way.':'Краткий обзор заказов в пути.','ORDER':'ЗАКАЗ','CUSTOMER':'КЛИЕНТ','TOTAL':'ИТОГО','DATE':'ДАТА','Processing':'В обработке','Shipped':'Отправлен','Delivered':'Доставлен','Customers.':'Клиенты.','Lovely people, lovely choices.':'Замечательные люди и выбор.','EMAIL':'ЭЛЕКТРОННАЯ ПОЧТА','SPENT':'ПОТРАЧЕНО','LAST ORDER':'ПОСЛЕДНИЙ ЗАКАЗ','Product name':'Название товара','Compare at price':'Старая цена','Image file ID':'ID файла изображения','Short description':'Краткое описание','Save product':'Сохранить товар','Cancel':'Отмена','Category name':'Название категории','Save category':'Сохранить категорию','Move or remove this category’s products first.':'Сначала переместите или удалите товары этой категории.'
});
Object.assign(translations.kz, {
  'Choose language':'Тілді таңдау','Toggle dark mode':'Қараңғы режимді ауыстыру','Search products':'Тауарларды іздеу','Search':'Іздеу','Phone number':'Телефон нөмірі','Address (optional)':'Мекенжай (міндетті емес)','Street, city, postal code':'Көше, қала, пошта индексі','/ Shop':'/ Дүкен','/ Details':'/ Мәлімет','JULIA M. · VERIFIED CUSTOMER':'ЮЛИЯ М. · ТЕКСЕРІЛГЕН САТЫП АЛУШЫ','NOAH P. · VERIFIED CUSTOMER':'НОА П. · ТЕКСЕРІЛГЕН САТЫП АЛУШЫ','PRIYA S. · VERIFIED CUSTOMER':'ПРИЯ С. · ТЕКСЕРІЛГЕН САТЫП АЛУШЫ','Instagram ↗':'Instagram ↗'
});
Object.assign(translations.ru, {
  'Choose language':'Выбрать язык','Toggle dark mode':'Переключить тёмную тему','Search products':'Поиск товаров','Search':'Поиск','Phone number':'Номер телефона','Address (optional)':'Адрес (необязательно)','Street, city, postal code':'Улица, город, почтовый индекс','/ Shop':'/ Магазин','/ Details':'/ Подробнее','JULIA M. · VERIFIED CUSTOMER':'ЮЛИЯ М. · ПРОВЕРЕННЫЙ ПОКУПАТЕЛЬ','NOAH P. · VERIFIED CUSTOMER':'НОА П. · ПРОВЕРЕННЫЙ ПОКУПАТЕЛЬ','PRIYA S. · VERIFIED CUSTOMER':'ПРИЯ С. · ПРОВЕРЕННЫЙ ПОКУПАТЕЛЬ','Instagram ↗':'Instagram ↗'
});
Object.assign(translations.kz, {
  'Message us on WhatsApp ↗':'WhatsApp арқылы жазыңыз ↗','YOUR STUDIO':'СТУДИЯҢЫЗ','▦ Overview':'▦ Шолу','◈ Products':'◈ Тауарлар','◇ Categories':'◇ Санаттар','▤ Orders':'▤ Тапсырыстар','♙ Customers':'♙ Клиенттер','The Everyday Shirt':'Күнделікті жейде','A considered everyday favourite.':'Күнделікті киюге арналған сүйікті киім.',
  'Toggle dark mode':'Қараңғы режимді ауыстыру','Open menu':'Мәзірді ашу','Search':'Іздеу','Your bag':'Себетіңіз','Cart':'Себет','Wishlist':'Таңдаулылар','Subscribe':'Жазылу','V. 2025':'V. 2025','Today':'Бүгін','Yesterday':'Кеше','new this week':'осы аптада жаңа',
  'Image path in images/products/':'Сурет жолы (images/products/)'
});
Object.assign(translations.ru, {
  'Message us on WhatsApp ↗':'Написать нам в WhatsApp ↗','YOUR STUDIO':'ВАША СТУДИЯ','▦ Overview':'▦ Обзор','◈ Products':'◈ Товары','◇ Categories':'◇ Категории','▤ Orders':'▤ Заказы','♙ Customers':'♙ Клиенты','The Everyday Shirt':'Повседневная рубашка','A considered everyday favourite.':'Любимая вещь на каждый день.',
  'Toggle dark mode':'Переключить тёмную тему','Open menu':'Открыть меню','Search':'Поиск','Your bag':'Ваша корзина','Cart':'Корзина','Wishlist':'Избранное','Subscribe':'Подписаться','V. 2025':'V. 2025','Today':'Сегодня','Yesterday':'Вчера','new this week':'новых за эту неделю',
  'Image path in images/products/':'Путь к изображению (images/products/)'
});
Object.assign(translations.kz,{Price:'Бағасы','Add to bag +':'Себетке қосу +'});
Object.assign(translations.ru,{Price:'Цена','Add to bag +':'В корзину +'});
Object.assign(translations.kz, {'T-shirt':'Футболка','Dress':'Көйлек','Trousers':'Шалбар','Hoodie':'Худи','Shoes':'Аяқ киім','Other':'Басқа'});
Object.assign(translations.ru, {'T-shirt':'Футболка','Dress':'Платье','Trousers':'Брюки','Hoodie':'Худи','Shoes':'Обувь','Other':'Другое'});
translations.en = new Proxy({}, { get: (_, key) => String(key) });
let currentLanguage = localStorage.getItem('velora-language') || 'kz';
let titleEnglish = document.title;
let titleTranslated = '';
const t = (phrase) => (translations[currentLanguage] && translations[currentLanguage][phrase]) || phrase;
const normalizeI18nText = (value) => value.replace(/\s+/g, ' ').trim();
function translateMixedText(value) {
  if(currentLanguage==='en')return value;
  return Object.keys(translations[currentLanguage]).sort((a,b)=>b.length-a.length).reduce((text,key)=>{
    if(!text.includes(key))return text;
    if(/^[A-Za-z]+$/.test(key))return text.replace(new RegExp(`\\b${key}\\b`,'g'),translations[currentLanguage][key]);
    return text.split(key).join(translations[currentLanguage][key]);
  },value);
}
function addLanguageSwitcher() {
  document.querySelectorAll('.site-header .header-actions').forEach((actions) => {
    if (actions.querySelector('.language-switcher')) return;
    const group = document.createElement('div'); group.className = 'language-switcher'; group.setAttribute('aria-label', 'Choose language');
    [['kz','KZ'],['ru','RU'],['en','EN']].forEach(([lang,label]) => { const button=document.createElement('button');button.type='button';button.dataset.language=lang;button.textContent=label;button.setAttribute('aria-label', label);group.append(button); });
    const theme = actions.querySelector('.theme-toggle'); actions.insertBefore(group, theme || null);
  });
  const adminNav=document.querySelector('.admin-sidebar');
  if(adminNav&&!document.querySelector('.admin-language-switcher')) { const group=document.createElement('div');group.className='language-switcher admin-language-switcher';[['kz','KZ'],['ru','RU'],['en','EN']].forEach(([lang,label])=>{const b=document.createElement('button');b.type='button';b.dataset.language=lang;b.textContent=label;group.append(b)});adminNav.insertBefore(group,adminNav.querySelector('.admin-label')); }
}
function applyLanguage(lang=currentLanguage) {
  currentLanguage = translations[lang] ? lang : 'kz';
  localStorage.setItem('velora-language', currentLanguage);
  document.documentElement.lang = currentLanguage === 'kz' ? 'kk' : currentLanguage;
  document.querySelectorAll('[data-i18n]').forEach(el => { const key=el.dataset.i18n;el.textContent=t(key); });
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
  while((node=walker.nextNode())) { if(node.parentElement?.closest('script,style,.product-grid,.cart-items,.product-detail,.search-result-grid,.admin-panel table,.admin-nav,.language-switcher')) continue;const original=node.__veloraEnglish || normalizeI18nText(node.nodeValue);if(node.__veloraEnglish===undefined)node.__veloraEnglish=original;const translated=t(original);if(node.__veloraLast)node.nodeValue=node.nodeValue.replace(node.__veloraLast,translated);else node.nodeValue=node.nodeValue.replace(original,translated);node.__veloraLast=translated; }
  document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>['placeholder','aria-label','title'].forEach(attr=>{if(!el.hasAttribute(attr))return;const original=el.dataset[`i18n${attr.replace(/(^|-)(.)/g,(_,a,c)=>c.toUpperCase())}`]||el.getAttribute(attr);el.dataset[`i18n${attr.replace(/(^|-)(.)/g,(_,a,c)=>c.toUpperCase())}`]=original;el.setAttribute(attr,translateMixedText(original));}));
  document.querySelectorAll('.language-switcher button').forEach(b=>{const active=b.dataset.language===currentLanguage;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
  if(window.renderProducts)window.renderProducts();
  document.title=translateMixedText(titleEnglish || document.title);
  titleTranslated=document.title;
  translateTextNodes(document.body);
  if(window.renderAdminTranslations)window.renderAdminTranslations();
}
function translateTextNodes(root) {
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;
  while((node=walker.nextNode())) {
    if(!node.nodeValue.trim()||node.parentElement?.closest('script,style,.language-switcher'))continue;
    const original=node.__veloraEnglish||normalizeI18nText(node.nodeValue);
    if(node.__veloraEnglish===undefined)node.__veloraEnglish=original;
    const translated=t(original)!==original?t(original):translateMixedText(original);
    if(node.__veloraLast)node.nodeValue=node.nodeValue.replace(node.__veloraLast,translated);
    else node.nodeValue=node.nodeValue.replace(original,translated);
    node.__veloraLast=translated;
  }
  root.querySelectorAll?.('[placeholder],[aria-label],[title]').forEach(el=>['placeholder','aria-label','title'].forEach(attr=>{if(!el.hasAttribute(attr))return;const dataKey=`i18n${attr.replace(/(^|-)(.)/g,(_,a,c)=>c.toUpperCase())}`,original=el.dataset[dataKey]||el.getAttribute(attr);el.dataset[dataKey]=original;el.setAttribute(attr,translateMixedText(original));}));
}
document.addEventListener('click',event=>{const button=event.target.closest('[data-language]');if(button)applyLanguage(button.dataset.language);});
document.addEventListener('DOMContentLoaded',()=>{addLanguageSwitcher();applyLanguage(currentLanguage);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>{if(node.nodeType===Node.TEXT_NODE)translateTextNodes(node.parentElement);else if(node.nodeType===Node.ELEMENT_NODE)translateTextNodes(node);}))).observe(document.body,{childList:true,subtree:true});const title=document.querySelector('title');if(title)new MutationObserver(()=>{if(title.textContent!==titleTranslated)titleEnglish=title.textContent;const translated=translateMixedText(titleEnglish);if(title.textContent!==translated)title.textContent=translated;titleTranslated=translated;}).observe(title,{childList:true,characterData:true,subtree:true});});
