/* Single source of truth for the starter product catalogue.
   Place a product image in images/products/ and update its image path here. */
window.VELORA_PRODUCTS = [
  { id:'p01', name:'The Everyday Linen Shirt', image:'images/products/everyday-linen-shirt.svg', price:8800, category:'Women', description:'An easy layer for slow mornings and full days. Cut from airy, breathable linen with a relaxed shape that feels just right.', stock:10, oldPrice:11000, badge:'20% OFF', isNew:true },
  { id:'p02', name:'Relaxed Tailored Trouser', image:'images/products/relaxed-tailored-trouser.svg', price:11200, category:'Women', description:'A flattering drape with the ease of your favourite pair. Finished with a soft waistband, deep pockets, and a clean tailored line.', stock:8, oldPrice:14000, badge:'20% OFF', isNew:true },
  { id:'p03', name:'The Weekend Knit', image:'images/products/weekend-knit.svg', price:9600, category:'Men', description:'A quietly handsome knit in soft, breathable cotton. An everyday layer made for all the little in-between moments.', stock:12, oldPrice:null, badge:'JUST IN', isNew:true },
  { id:'p04', name:'Soft Structure Tote', image:'images/products/soft-structure-tote.svg', price:7400, category:'Accessories', description:'A thoughtful carryall that holds all your everyday essentials. Crafted with room to roam, inside and out.', stock:6, oldPrice:9200, badge:'20% OFF', isNew:false },
  { id:'p05', name:'City Walk Loafer', image:'images/products/city-walk-loafer.svg', price:12990, category:'Shoes', description:'Meet your go-anywhere shoe. A clean, considered silhouette with a cushioned sole designed for a full day on your feet.', stock:9, oldPrice:null, badge:'', isNew:true },
  { id:'p06', name:'Sunday Cotton Tee', image:'images/products/sunday-cotton-tee.svg', price:4800, category:'Men', description:'The tee you reach for without thinking. Made from soft organic cotton with an easy, everyday fit.', stock:20, oldPrice:null, badge:'', isNew:false },
  { id:'p07', name:'The Everyday Midi', image:'images/products/everyday-midi.svg', price:11800, category:'Women', description:'An effortless throw-on-and-go dress, made for wherever the day takes you. Light, lovely, and easy to make your own.', stock:7, oldPrice:14800, badge:'20% OFF', isNew:false },
  { id:'p08', name:'Leather Weekender', image:'images/products/leather-weekender.svg', price:18600, category:'Accessories', description:'A considered companion for short escapes and everyday carry. Roomy, sturdy, and all the better for a little adventure.', stock:4, oldPrice:null, badge:'', isNew:true }
];
